### ISSUE TITLE
Question about read/write char

### ISSUE THREAD

**Issue by oulton** [imabot2/serialib#18]
It can read or write Byte char.  how to read/write Byte unsigned char(0-255)?

**Comment by imabot2** [comment]
You can cast the value returned by the funcion `readChar()`

```
unsigned char val;
val = (unsigned char) readChar  (pByte);
```

Check this page (sorry, it's in French) : [https://lucidar.me/fr/c-class/lesson-03-04-type-casting/](https://lucidar.me/fr/c-class/lesson-03-04-type-casting/)
