### ISSUE TITLE
New Example file

### ISSUE THREAD

**Issue by odbee** [imabot2/serialib#22]
hello, i have seen other people in the issues having struggled with this so i would like to emphasize again that it would be VERY helpful if you created a third example file, that goes through receiving and sending strings, chars and bytes (especially receiving) for us people who arent fully proficient in this code.

it would help alot to have a fully functional cpp file that  uses these functions for us to understand.

I am very sure the user from this (https://github.com/imabot2/serialib/issues/11) issue knew that the function `readBytes()` exists but he, like me struggled with using this function, because there is no proper documentation or example for it.

thanks in advance!

**Comment by imabot2** [comment]
Hi, could you tell me more details about what kind of example you expect more precisely?

**Comment by odbee** [comment]
an example for readString would help A LOT, took me ages to figure out by myself, especially with the amount of documentation prvided

**Comment by imabot2** [comment]
Here are some examples:
[readBytes / writeBytes](https://lucidar.me/en/serialib/read-and-write-array-of-bytes-on-serial-port-in-c-cpp/)
[readString / writeString](https://lucidar.me/en/serialib/read-and-write-strings-on-serial-port-in-c-cpp/)
