### ISSUE TITLE
After the read thread is started, the write operation is performed.  In this case, the write delay is very high, up to 70+ms

### ISSUE THREAD

**Issue by chinaZoulx** [imabot2/serialib#35]
The serial port type is RS232
![image](https://github.com/user-attachments/assets/66407973-7eab-461c-a65e-7b2ffc9b09c0)

write thread :
`for (;;) {
        int ret = mSerial.readBytes(recvBuffer, sizeof(recvBuffer), 10, 1000);
        if (ret < 0) {
            LOGE("read data error. ret = {}", ret);
            return -1;
        }
        if (ret == 0){
            continue;
        }
        mDataHandler(recvBuffer, ret);
    }
`

write function:
`int SerialManager::send(const void *data, int len) {
    if (!mSerial.isDeviceOpen()) {
        return 0;
    }
    int ret = mSerial.writeBytes(data, len);
    return ret;
}`

**Comment by imabot2** [comment]
I don't understand your problem. Can you explain what is our issue?

**Comment by imabot2** [comment]
I don't understand your problem. Can you explain what is our issue?

**Comment by imabot2** [comment]
I don't understand your problem. Can you explain what is our issue?
