### ISSUE TITLE
cannot connect to my ft232

### ISSUE THREAD

**Issue by Basilisvirus** [imabot2/serialib#7]
I think I am missing something, but both of your examples cannot connect to my ft232.

I am on windows 10, with code:blocks 20.03, mingw compiler (and i also tried cygwin compiler), with both of your examples. 

Both fail on

`if (errorOpening!=1) return errorOpening;`

I have a atmega328p connected to the ft232 (so an arduino), which i can access from both arduino IDE and TeraTerm. I can send/receive data from both arduino and TeraTerm, So the device is there, working properly.

i defined/changed the com port to match my com port `#define SERIAL_PORT "COM5"` and i have no errors when compiling.

I include the libraries are shown from your examples:

```
#include "serialib.h"
#include <unistd.h>
#include <stdio.h>

```

I think there might be an issue with drivers?

**Comment by maxgerhardt** [comment]
Can you open the serial adapter using [hterm.exe](https://www.der-hammer.info/pages/terminal.html)?

**Comment by Basilisvirus** [comment]
Thank you for your comment. I gave up on that and ended up using this library: https://www.teuniz.net/RS-232/ which works great
