### ISSUE TITLE
Add UART formatting options

### ISSUE THREAD

**Issue by maxgerhardt** [imabot2/serialib#8]
This library looks great, but is currently lacking the ability to set the
* number data bits
* parity type (none, even, odd)
* stop bits (1, 2, 1.5)

It is all hardcoded in e.g. 

https://github.com/imabot2/serialib/blob/8e7e23aad8a3bcd31f9776799e3f8c6b84025a87/lib/serialib.cpp#L204-L206

**Comment by imabot2** [comment]
Yes, but I will not have enough time to update the library.

**Comment by maxgerhardt** [comment]
I'll do a PR then :)

**Comment by imabot2** [comment]
Sorry for the late answer. I didn't see you pull request. It's merged.
Thank you for you contribution.
