### ISSUE TITLE
What licence is this under?

### ISSUE THREAD

**Issue by itzandroidtab** [imabot2/serialib#9]
In the repo there is a GPL-3.0 License file. In the serialib header and source file there is a notice this is a "licence-free software".

What is the correct license information?

**Comment by imabot2** [comment]
It's a free software, you can do whatever you want with it.
Best regards
Philippe

Le dim. 1 août 2021 à 15:48, itzandroidtab ***@***.***> a
écrit :

**Comment by itzandroidtab** [comment]
Thank you for your response
